services:
  mysql:
    image: mysql:8
    container_name: go-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - go_mysql_data:/var/lib/mysql

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-migrate
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_DSN: ${DB_DSN_DOCKER}
    command: ["./migrate"]
    volumes:
      - ./migrations:/app/migrations

  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_DSN: ${DB_DSN_DOCKER}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./migrations:/app/migrations

volumes:
  go_mysql_data:

